version: "3"

services:
  reverse:
    container_name: reverse
    image: 'nginx'
    hostname: ${SERVER_HOSTNAME}
    networks:
      - trivianetwork
    restart: always
    ports:
      - 80:80
      - 443:443
      - 5000:5000
      - 8081:8081
    links:
      - "appclient:appclient"
      - "appserver:appserver"
      - "mongodb:mongodb"
      - "mongoexpress:mongoexpress"
    volumes:
      - ${PATH_TO_CONF}:/etc/nginx/nginx.conf
      - ${PATH_TO_CERTS}:/etc/letsencrypt
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    volumes:
      - 'mongodata:/data/db'
    networks:
      - trivianetwork
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_ROOT_DATABASE}
      MONGO_INITDB_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      MONGO_INITDB_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      MONGO_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  appclient:
    build: 
      context: ./appclient/
    container_name: 'appclient'
    restart: 'always'
    volumes: 
      - ./appclient/public_html:/usr/local/apache2/htdocs/       
    depends_on:
      - appserver  
    links:
      - "appserver:appserver"
    networks:
      - trivianetwork      
  appserver:
    build: 
      context: ./
    container_name: 'appserver'
    restart: 'always'
    hostname: ${SERVER_API_HOSTNAME}
    depends_on:
      - mongodb
    links:
      - "mongodb:mongodb"
    networks:
      - trivianetwork     
    volumes:
      - ./appserver/dist:/usr/src/app/dist   
      - ./schemas:/usr/src/app/schemas   
  mongoexpress:
    image: mongo-express
    container_name: mongo-express
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - mongodb    
    networks:
      - trivianetwork
    links:
      - "mongodb:mongodb"
networks:
  trivianetwork:
volumes:
  mongodata:
  letsencrypt: