version: "3"

services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    volumes:
      - 'mongodata:/data/db'
    networks:
      - beuschernet
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_ROOT_DATABASE}
      MONGO_INITDB_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      MONGO_INITDB_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      MONGO_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  appclient:
    build: 
      context: ./appclient
    container_name: 'appclient'
    restart: 'always'
    hostname: ${SERVER_HOSTNAME}
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ./appclient/public_html:/usr/local/apache2/htdocs/       
    depends_on:
      - appserver  
    links:
      - "appserver:appserver"
    networks:
      - beuschernet      
  appserver:
    build: 
      context: ./
    container_name: 'appserver'
    restart: 'always'
    hostname: ${SERVER_HOSTNAME}
    ports:
      - ${API_PORT}
    depends_on:
      - mongodb
    links:
      - "mongodb:mongodb"
    networks:
      - beuschernet     
    volumes:
      - ./appserver/dist:/usr/src/app/dist   
      - ./schemas:/usr/src/app/schemas   
  mongoexpress:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ""
      ME_CONFIG_BASICAUTH_PASSWORD: ""
    depends_on:
      - mongodb    
    networks:
      - beuschernet
    links:
      - "mongodb:mongodb"
networks:
  beuschernet:
volumes:
  mongodata: